#theme: jekyll-theme-cayman
title: Seong Hok Lao's Page
remote_theme: pages-themes/leap-day@v0.2.0
titles_from_headings:
  enabled:     false
  # strip_title: true
  # collections: true

github:
  is_project_page: false
